global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'stream-monitoring'
    static_configs:
      - targets: ['stream-monitoring:9100']
    metrics_path: /metrics

  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['flink-jobmanager:9249']

  - job_name: 'flink-taskmanager'
    static_configs:
      - targets: ['flink-taskmanager:9249']

  - job_name: 'clip-detector'
    static_configs:
      - targets: ['flink-taskmanager:9250']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
